<html>
<head>
<title>Unified logs</title>
</head>
<body>
<?php

if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on')
     $url = "https://";
else
     $url = "http://";
// Append the host(domain name, ip) to the URL.
$url.= $_SERVER['HTTP_HOST'];

// Append the requested resource location to the URL
$url.= $_SERVER['REQUEST_URI'];

$url_components = parse_url($url);

// Use parse_str() function to parse the
// string passed via URL
parse_str($url_components['query'], $args);


$myfile = file_get_contents('./restricted/secret.txt', true);



$query = "{\"query\":{\"bool\":{\"must\":[{\"wildcard\":{\"meta\":\"*". $args['search']   ."*\"}}]}},\"sort\":[{\"timestamp\":\"desc\"}],\"_source\":[\"text\",\"subject\",\"date\",\"meta\"]}";

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://es-unified7.cern.ch/es/unified-logs/_doc/_search?size=50');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_POSTFIELDS, $query);

curl_setopt($ch, CURLOPT_USERPWD, rtrim($myfile));


$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result_curl = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);



// Read the JSON file
$json = file_get_contents('test.json');

// Decode the JSON file
$json_data = json_decode($result_curl, false);

$real_data = $json_data->hits->hits;

echo '<table style="border: 1px solid black">';
foreach($real_data as $result){
  echo '<tr>';
    echo '<th style="border: 1px solid black; font-size:30px">'.$result->_source->subject.'</th>';
    echo '<th style="border: 1px solid black; font-size:30px">'.$result->_source->date.'</th>';
  echo '</tr>';

  echo '<tr>';
    echo '<td style="border: 1px solid black"></td>';
    echo '<td style="white-space: pre-line; border: 1px solid black">'.$result->_source->text.'</td>';
  echo '</tr>';
}
echo '</table>';


?>
</body>
</html>