name: ShellCheck

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
    - name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ secrets.github_token }}
        level: info
        fail_on_error: true
        shellcheck_flags: '--shell=bash -x'
        reporter: github-pr-review
        pattern: "*.sh"
