name: ShellCheck/push

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
    - name: Get Diff Action
      uses: technote-space/get-diff-action@v1.2.8
      with:
        SUFFIX_FILTER: .sh
    - name: Install ShellCheck
      run: |
        sudo apt-get install shellcheck
      if: env.GIT_DIFF
    - name: Lint with ShellCheck
      run: |
        shellcheck --shell=bash -x ${{ env.GIT_DIFF }}
      if: env.GIT_DIFF
