name: Check Json format

on: [push, pull_request]

jobs:
  jsonlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
    - name: Get Diff Action
      uses: technote-space/get-diff-action@v1.2.8
      with:
        SUFFIX_FILTER: .json
    - name: Install node
      run: |
        sudo apt install nodejs
    - name: Install jsonlint
      run: |
        sudo npm install -g jsonlint
    - name: Lint with jsonlint
      run: |
        for file in ${{ env.GIT_DIFF }}; do npx jsonlint $file; done
      if: env.GIT_DIFF
